services:

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=contas'
      - 'POSTGRES_PASSWORD=postgre'
      - 'POSTGRES_USER=postgre'
    ports:
      - '5432:5432'

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/contas
      SPRING_DATASOURCE_USERNAME: postgre
      SPRING_DATASOURCE_PASSWORD: postgre


